name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - bot/v*

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.event.head_commit.message, 'chore: preparing release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          default_prerelease_bump: false
      - name: Create a GitHub release
        if: steps.tag_version.outputs.new_tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
            python-version: 3.8
      - name: Install pip
        run: pip install -r requirements/pip.txt
      - name: Build package
        run: make build-pythonpackage
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
            user: __token__
            password: ${{ secrets.PYPI_UPLOAD_TOKEN }}
